### ISSUE TITLE
Image Builds Fail

### ISSUE THREAD

**Issue by danehans** [tetratelabs/istio#585]
https://github.com/tetratelabs/istio/commit/c845bff65824db175474513335eba95c03add8c9 introduced a regression. The commit updated the Go and BoringGo setup scripts by adding [set -u](http://linuxcommand.org/lc3_man_pages/seth.html) which treats unset variables as an error and introduced the `ISTIO_MINOR_VER` unset variable. See [this](https://github.com/tetratelabs/istio/actions/runs/1556542115) failed workflow as an example.

cc: @yskopets @pmerrison

**Comment by yskopets** [comment]
@danehans The [workflow in question](https://github.com/tetratelabs/istio/actions/runs/1556542115) failed for a different reason.

#584 (support for `Istio 1.12`) was merged into `tetrate-workflow` branch (where all development happens) but never ported back into `tetrate-release-1.12` and `tetratefips-release-1.12` due to a [failure in GitHub Automation](https://github.com/tetratelabs/istio/actions/runs/1544779835).

I've ported #584 back into `tetrate-release-1.12` and `tetratefips-release-1.12` now (see #598 and #580).

`create-test-images` step [is now successful](https://github.com/tetratelabs/istio/runs/4726351783?check_suite_focus=true).

I cannot confirm any regression in #584.

**Comment by danehans** [comment]
Closing due to above comment.
