### ISSUE TITLE
FIPS Proxy Binary Fails to Build

### ISSUE THREAD

**Issue by danehans** [tetratelabs/istio#587]
It appears that https://github.com/tetratelabs/istio/commit/c845bff65824db175474513335eba95c03add8c9 may have introduced a regression to the `check_already_built` step of the `build_fips_proxy` job. See [this](https://github.com/tetratelabs/istio/runs/4720933023?check_suite_focus=true) failed workflow for details.

xref: https://github.com/tetratelabs/istio/issues/585

cc: @pmerrison

**Comment by yskopets** [comment]
@danehans I've explained [in the comment](https://github.com/tetratelabs/istio/issues/585#issuecomment-1006531999) to #585 that GHA workflow was failing since #584 was never ported back into `tetrate-release-1.12` and `tetratefips-release-1.12` branches.

Once I backported #584, the workflow [is working](https://github.com/tetratelabs/istio/runs/4726407671?check_suite_focus=true).

I cannot confirm any regression in #584.

**Comment by danehans** [comment]
Closing due to above comment.
